- name: copy ceph user key
  copy:
    src: "{{item}}"
    dest: /etc/ceph/{{item}}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - ceph.client.cinder.keyring

- name: Start the Compute service including its dependencies and configure them to start automatically when the system boots
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - libvirtd.service 
    - openstack-nova-compute.service 
